addSbtPlugin("org.typelevel"                     % "sbt-typelevel-site" % "0.8.7")
addSbtPlugin("org.scalameta"                     % "sbt-scalafmt"       % "2.5.6")
addSbtPlugin("org.scoverage"                     % "sbt-scoverage"      % "2.4.2")
addSbtPlugin("org.scoverage"                     % "sbt-coveralls"      % "1.3.15")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"   % "3.0.2")
addSbtPlugin("com.github.sbt"                    % "sbt-ci-release"     % "1.11.2")
addSbtPlugin("pl.project13.scala"                % "sbt-jmh"            % "0.4.8")
