name: Benchmarks

on:
  push:
    branches: [ main, series/6.x ]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: sbt/setup-sbt@v1
      - name: Cache SBT
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/coursier/v1
            ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Benchmarks
        run: sbt "project fs2-aws-benchmarks" "jmh:run -i 10 -wi 10 -f1 -t1 -rf json -rff kinesis_bench.json"
      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: fs2-aws-benchmarks/kinesis_bench.json
