name: Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  site:
    name: Generate & Publish Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Setup sbt
        uses: sbt/setup-sbt@v1

      - name: Generate site
        run: sbt siteDocs/tlSite

      - name: Publish site
        if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/target/docs/site
          keep_files: true
